### ISSUE TITLE
Config tab inconsistently showing available options

### ISSUE THREAD

**Issue by DonutCables** [w00000dy/WLED-GUI#8]
**Describe the bug**
Going to the "Config" tab after selecting a light instance will sometimes show all of the "normal" settings you'd see when accessing the web version, but other times will only show the compact version with "More settings..." button which then opens a web instance in Firefox. 
As far as I know the settings are supposed to always be the compact version. 
In addition to this being inconsistent, I would like the option to always show the full version of the settings instead of needing to access the web version. 

**Desktop (please complete the following information):**
 - OS: Windows8.1
 - Version: 0.7.1.0

**Comment by WoodyLetsCode** [comment]
Hi,
thank you for reporting this bug. 😄 
I assume that you have enabled **Online Mode** for some lights and this is why _Config_ is inconsistent when you go through your lights. When **Online Mode** is enabled it will use the online version of WLED (like accessing WLED in your browser) instead of the local version.
Currently there is also another issue #3 that deals with this topic of the _settings_ page.
I'm planning to add the full _settings_ page in one of the next versions of WLED-GUI, but I'm waiting for Aircoookie/WLED#1630 to be implemented.
I guess it will be implemented in WLED v0.13.

So to have the full access to the _settings_ in WLED-GUI you probably have to wait for WLED version 0.13. 😞 
Is my assumption correct that you use **Online Mode**?

**Comment by DonutCables** [comment]
So I went poking more and finally found the option to toggle "Online Mode", so that does what I'd like for now. 
I wasn't using it previously, so I'm not sure why it was popping up inconsistently for a single instance of lights.

**Comment by WoodyLetsCode** [comment]
Can you tell me what version of WLED you use?
Do you use the same version for all your lights?

**Comment by DonutCables** [comment]
I'm using 0.12.0 for all of my ESP8266, but the one ESP32 I have connected right now I'm using the dev version of SoundReactive 0.12.0 that has the 2D animations partially enabled.

**Comment by WoodyLetsCode** [comment]
Do you see this inconsistency only in a specific light (for example the SoundReactive light) or in all lights?

**Comment by DonutCables** [comment]
I can't be sure, I was going through 4-5 different lights when I noticed it happening.

**Comment by w00000dy** [comment]
Will be fixed in latest version
